CREATE DATABASE IF NOT EXISTS api_database;

USE api_database;

CREATE TABLE newspapers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    column_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE articles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    body TEXT,
    newspaper_id INT,
    year INT,
    month INT,
    day INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (newspaper_id) REFERENCES newspapers(id)
);