// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ArticleCreateRequest defines model for ArticleCreateRequest.
type ArticleCreateRequest struct {
	Body      string     `json:"body"`
	Day       int        `json:"day"`
	Month     int        `json:"month"`
	Newspaper *Newspaper `json:"newspaper,omitempty"`
	Year      int        `json:"year"`
}

// ArticleResponse defines model for ArticleResponse.
type ArticleResponse struct {
	Body      string     `json:"body"`
	Day       int        `json:"day"`
	Id        int        `json:"id"`
	Month     int        `json:"month"`
	Newspaper *Newspaper `json:"newspaper,omitempty"`
	Year      int        `json:"year"`
}

// ArticleUpdateRequest defines model for ArticleUpdateRequest.
type ArticleUpdateRequest struct {
	Body      *string    `json:"body,omitempty"`
	Day       *int       `json:"day,omitempty"`
	Month     *int       `json:"month,omitempty"`
	Newspaper *Newspaper `json:"newspaper,omitempty"`
	Year      *int       `json:"year,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// Newspaper defines model for Newspaper.
type Newspaper struct {
	ColumnName string `json:"columnName"`
	Id         int    `json:"id"`
	Title      string `json:"title"`
}

// NewspaperCreateRequest defines model for NewspaperCreateRequest.
type NewspaperCreateRequest struct {
	ColumnName string `json:"columnName"`
	Title      string `json:"title"`
}

// NewspaperResponse defines model for NewspaperResponse.
type NewspaperResponse struct {
	ColumnName string `json:"columnName"`
	Id         int    `json:"id"`
	Title      string `json:"title"`
}

// NewspaperUpdateRequest defines model for NewspaperUpdateRequest.
type NewspaperUpdateRequest struct {
	ColumnName *string `json:"columnName,omitempty"`
	Title      *string `json:"title,omitempty"`
}

// CreateArticleJSONRequestBody defines body for CreateArticle for application/json ContentType.
type CreateArticleJSONRequestBody = ArticleCreateRequest

// UpdateArticleByIdJSONRequestBody defines body for UpdateArticleById for application/json ContentType.
type UpdateArticleByIdJSONRequestBody = ArticleUpdateRequest

// CreateNewspaperJSONRequestBody defines body for CreateNewspaper for application/json ContentType.
type CreateNewspaperJSONRequestBody = NewspaperCreateRequest

// UpdateNewspaperByIdJSONRequestBody defines body for UpdateNewspaperById for application/json ContentType.
type UpdateNewspaperByIdJSONRequestBody = NewspaperUpdateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateArticleWithBody request with any body
	CreateArticleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateArticle(ctx context.Context, body CreateArticleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteArticleById request
	DeleteArticleById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArticleById request
	GetArticleById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateArticleByIdWithBody request with any body
	UpdateArticleByIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateArticleById(ctx context.Context, id int, body UpdateArticleByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNewspaperWithBody request with any body
	CreateNewspaperWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNewspaper(ctx context.Context, body CreateNewspaperJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNewspaperById request
	DeleteNewspaperById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNewspaperById request
	GetNewspaperById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateNewspaperByIdWithBody request with any body
	UpdateNewspaperByIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateNewspaperById(ctx context.Context, id int, body UpdateNewspaperByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArticlesByNewspaperId request
	GetArticlesByNewspaperId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateArticleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateArticleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateArticle(ctx context.Context, body CreateArticleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateArticleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteArticleById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteArticleByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetArticleById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArticleByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateArticleByIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateArticleByIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateArticleById(ctx context.Context, id int, body UpdateArticleByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateArticleByIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNewspaperWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNewspaperRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNewspaper(ctx context.Context, body CreateNewspaperJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNewspaperRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteNewspaperById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNewspaperByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNewspaperById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNewspaperByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNewspaperByIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateNewspaperByIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNewspaperById(ctx context.Context, id int, body UpdateNewspaperByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateNewspaperByIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetArticlesByNewspaperId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArticlesByNewspaperIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateArticleRequest calls the generic CreateArticle builder with application/json body
func NewCreateArticleRequest(server string, body CreateArticleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateArticleRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateArticleRequestWithBody generates requests for CreateArticle with any type of body
func NewCreateArticleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/article")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteArticleByIdRequest generates requests for DeleteArticleById
func NewDeleteArticleByIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/article/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetArticleByIdRequest generates requests for GetArticleById
func NewGetArticleByIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/article/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateArticleByIdRequest calls the generic UpdateArticleById builder with application/json body
func NewUpdateArticleByIdRequest(server string, id int, body UpdateArticleByIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateArticleByIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateArticleByIdRequestWithBody generates requests for UpdateArticleById with any type of body
func NewUpdateArticleByIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/article/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateNewspaperRequest calls the generic CreateNewspaper builder with application/json body
func NewCreateNewspaperRequest(server string, body CreateNewspaperJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateNewspaperRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateNewspaperRequestWithBody generates requests for CreateNewspaper with any type of body
func NewCreateNewspaperRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/newspaper")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteNewspaperByIdRequest generates requests for DeleteNewspaperById
func NewDeleteNewspaperByIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/newspaper/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNewspaperByIdRequest generates requests for GetNewspaperById
func NewGetNewspaperByIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/newspaper/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateNewspaperByIdRequest calls the generic UpdateNewspaperById builder with application/json body
func NewUpdateNewspaperByIdRequest(server string, id int, body UpdateNewspaperByIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateNewspaperByIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateNewspaperByIdRequestWithBody generates requests for UpdateNewspaperById with any type of body
func NewUpdateNewspaperByIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/newspaper/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetArticlesByNewspaperIdRequest generates requests for GetArticlesByNewspaperId
func NewGetArticlesByNewspaperIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/newspaper/%s/articles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateArticleWithBodyWithResponse request with any body
	CreateArticleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateArticleResponse, error)

	CreateArticleWithResponse(ctx context.Context, body CreateArticleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateArticleResponse, error)

	// DeleteArticleByIdWithResponse request
	DeleteArticleByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteArticleByIdResponse, error)

	// GetArticleByIdWithResponse request
	GetArticleByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetArticleByIdResponse, error)

	// UpdateArticleByIdWithBodyWithResponse request with any body
	UpdateArticleByIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateArticleByIdResponse, error)

	UpdateArticleByIdWithResponse(ctx context.Context, id int, body UpdateArticleByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateArticleByIdResponse, error)

	// CreateNewspaperWithBodyWithResponse request with any body
	CreateNewspaperWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNewspaperResponse, error)

	CreateNewspaperWithResponse(ctx context.Context, body CreateNewspaperJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNewspaperResponse, error)

	// DeleteNewspaperByIdWithResponse request
	DeleteNewspaperByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteNewspaperByIdResponse, error)

	// GetNewspaperByIdWithResponse request
	GetNewspaperByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetNewspaperByIdResponse, error)

	// UpdateNewspaperByIdWithBodyWithResponse request with any body
	UpdateNewspaperByIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNewspaperByIdResponse, error)

	UpdateNewspaperByIdWithResponse(ctx context.Context, id int, body UpdateNewspaperByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNewspaperByIdResponse, error)

	// GetArticlesByNewspaperIdWithResponse request
	GetArticlesByNewspaperIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetArticlesByNewspaperIdResponse, error)
}

type CreateArticleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ArticleResponse
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateArticleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateArticleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteArticleByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteArticleByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteArticleByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetArticleByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ArticleResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetArticleByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArticleByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateArticleByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ArticleResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateArticleByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateArticleByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateNewspaperResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *NewspaperResponse
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateNewspaperResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNewspaperResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteNewspaperByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteNewspaperByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNewspaperByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNewspaperByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NewspaperResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNewspaperByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNewspaperByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateNewspaperByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NewspaperResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateNewspaperByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateNewspaperByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetArticlesByNewspaperIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ArticleResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetArticlesByNewspaperIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArticlesByNewspaperIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateArticleWithBodyWithResponse request with arbitrary body returning *CreateArticleResponse
func (c *ClientWithResponses) CreateArticleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateArticleResponse, error) {
	rsp, err := c.CreateArticleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateArticleResponse(rsp)
}

func (c *ClientWithResponses) CreateArticleWithResponse(ctx context.Context, body CreateArticleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateArticleResponse, error) {
	rsp, err := c.CreateArticle(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateArticleResponse(rsp)
}

// DeleteArticleByIdWithResponse request returning *DeleteArticleByIdResponse
func (c *ClientWithResponses) DeleteArticleByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteArticleByIdResponse, error) {
	rsp, err := c.DeleteArticleById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteArticleByIdResponse(rsp)
}

// GetArticleByIdWithResponse request returning *GetArticleByIdResponse
func (c *ClientWithResponses) GetArticleByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetArticleByIdResponse, error) {
	rsp, err := c.GetArticleById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArticleByIdResponse(rsp)
}

// UpdateArticleByIdWithBodyWithResponse request with arbitrary body returning *UpdateArticleByIdResponse
func (c *ClientWithResponses) UpdateArticleByIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateArticleByIdResponse, error) {
	rsp, err := c.UpdateArticleByIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateArticleByIdResponse(rsp)
}

func (c *ClientWithResponses) UpdateArticleByIdWithResponse(ctx context.Context, id int, body UpdateArticleByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateArticleByIdResponse, error) {
	rsp, err := c.UpdateArticleById(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateArticleByIdResponse(rsp)
}

// CreateNewspaperWithBodyWithResponse request with arbitrary body returning *CreateNewspaperResponse
func (c *ClientWithResponses) CreateNewspaperWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNewspaperResponse, error) {
	rsp, err := c.CreateNewspaperWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNewspaperResponse(rsp)
}

func (c *ClientWithResponses) CreateNewspaperWithResponse(ctx context.Context, body CreateNewspaperJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNewspaperResponse, error) {
	rsp, err := c.CreateNewspaper(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNewspaperResponse(rsp)
}

// DeleteNewspaperByIdWithResponse request returning *DeleteNewspaperByIdResponse
func (c *ClientWithResponses) DeleteNewspaperByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteNewspaperByIdResponse, error) {
	rsp, err := c.DeleteNewspaperById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNewspaperByIdResponse(rsp)
}

// GetNewspaperByIdWithResponse request returning *GetNewspaperByIdResponse
func (c *ClientWithResponses) GetNewspaperByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetNewspaperByIdResponse, error) {
	rsp, err := c.GetNewspaperById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNewspaperByIdResponse(rsp)
}

// UpdateNewspaperByIdWithBodyWithResponse request with arbitrary body returning *UpdateNewspaperByIdResponse
func (c *ClientWithResponses) UpdateNewspaperByIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNewspaperByIdResponse, error) {
	rsp, err := c.UpdateNewspaperByIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNewspaperByIdResponse(rsp)
}

func (c *ClientWithResponses) UpdateNewspaperByIdWithResponse(ctx context.Context, id int, body UpdateNewspaperByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNewspaperByIdResponse, error) {
	rsp, err := c.UpdateNewspaperById(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNewspaperByIdResponse(rsp)
}

// GetArticlesByNewspaperIdWithResponse request returning *GetArticlesByNewspaperIdResponse
func (c *ClientWithResponses) GetArticlesByNewspaperIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetArticlesByNewspaperIdResponse, error) {
	rsp, err := c.GetArticlesByNewspaperId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArticlesByNewspaperIdResponse(rsp)
}

// ParseCreateArticleResponse parses an HTTP response from a CreateArticleWithResponse call
func ParseCreateArticleResponse(rsp *http.Response) (*CreateArticleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateArticleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ArticleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteArticleByIdResponse parses an HTTP response from a DeleteArticleByIdWithResponse call
func ParseDeleteArticleByIdResponse(rsp *http.Response) (*DeleteArticleByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteArticleByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetArticleByIdResponse parses an HTTP response from a GetArticleByIdWithResponse call
func ParseGetArticleByIdResponse(rsp *http.Response) (*GetArticleByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArticleByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArticleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateArticleByIdResponse parses an HTTP response from a UpdateArticleByIdWithResponse call
func ParseUpdateArticleByIdResponse(rsp *http.Response) (*UpdateArticleByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateArticleByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArticleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateNewspaperResponse parses an HTTP response from a CreateNewspaperWithResponse call
func ParseCreateNewspaperResponse(rsp *http.Response) (*CreateNewspaperResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNewspaperResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest NewspaperResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteNewspaperByIdResponse parses an HTTP response from a DeleteNewspaperByIdWithResponse call
func ParseDeleteNewspaperByIdResponse(rsp *http.Response) (*DeleteNewspaperByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNewspaperByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetNewspaperByIdResponse parses an HTTP response from a GetNewspaperByIdWithResponse call
func ParseGetNewspaperByIdResponse(rsp *http.Response) (*GetNewspaperByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNewspaperByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NewspaperResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateNewspaperByIdResponse parses an HTTP response from a UpdateNewspaperByIdWithResponse call
func ParseUpdateNewspaperByIdResponse(rsp *http.Response) (*UpdateNewspaperByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateNewspaperByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NewspaperResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetArticlesByNewspaperIdResponse parses an HTTP response from a GetArticlesByNewspaperIdWithResponse call
func ParseGetArticlesByNewspaperIdResponse(rsp *http.Response) (*GetArticlesByNewspaperIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArticlesByNewspaperIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ArticleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new article
	// (POST /article)
	CreateArticle(c *gin.Context)
	// Delete an article by ID
	// (DELETE /article/{id})
	DeleteArticleById(c *gin.Context, id int)
	// Get an article by ID
	// (GET /article/{id})
	GetArticleById(c *gin.Context, id int)
	// Update an article by ID
	// (PATCH /article/{id})
	UpdateArticleById(c *gin.Context, id int)
	// Create a new newspaper
	// (POST /newspaper)
	CreateNewspaper(c *gin.Context)
	// Delete a newspaper by ID
	// (DELETE /newspaper/{id})
	DeleteNewspaperById(c *gin.Context, id int)
	// Find newspaper by ID
	// (GET /newspaper/{id})
	GetNewspaperById(c *gin.Context, id int)
	// Update a newspaper by ID
	// (PATCH /newspaper/{id})
	UpdateNewspaperById(c *gin.Context, id int)
	// Get all articles by newspaper ID
	// (GET /newspaper/{id}/articles)
	GetArticlesByNewspaperId(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateArticle operation middleware
func (siw *ServerInterfaceWrapper) CreateArticle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateArticle(c)
}

// DeleteArticleById operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticleById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteArticleById(c, id)
}

// GetArticleById operation middleware
func (siw *ServerInterfaceWrapper) GetArticleById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArticleById(c, id)
}

// UpdateArticleById operation middleware
func (siw *ServerInterfaceWrapper) UpdateArticleById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateArticleById(c, id)
}

// CreateNewspaper operation middleware
func (siw *ServerInterfaceWrapper) CreateNewspaper(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNewspaper(c)
}

// DeleteNewspaperById operation middleware
func (siw *ServerInterfaceWrapper) DeleteNewspaperById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNewspaperById(c, id)
}

// GetNewspaperById operation middleware
func (siw *ServerInterfaceWrapper) GetNewspaperById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNewspaperById(c, id)
}

// UpdateNewspaperById operation middleware
func (siw *ServerInterfaceWrapper) UpdateNewspaperById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNewspaperById(c, id)
}

// GetArticlesByNewspaperId operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesByNewspaperId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArticlesByNewspaperId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/article", wrapper.CreateArticle)
	router.DELETE(options.BaseURL+"/article/:id", wrapper.DeleteArticleById)
	router.GET(options.BaseURL+"/article/:id", wrapper.GetArticleById)
	router.PATCH(options.BaseURL+"/article/:id", wrapper.UpdateArticleById)
	router.POST(options.BaseURL+"/newspaper", wrapper.CreateNewspaper)
	router.DELETE(options.BaseURL+"/newspaper/:id", wrapper.DeleteNewspaperById)
	router.GET(options.BaseURL+"/newspaper/:id", wrapper.GetNewspaperById)
	router.PATCH(options.BaseURL+"/newspaper/:id", wrapper.UpdateNewspaperById)
	router.GET(options.BaseURL+"/newspaper/:id/articles", wrapper.GetArticlesByNewspaperId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTU/rOBT9K9GdWUZNCkiDsqMwoGqkzhN6b4VYmPjSGiW2sV1QVPW/P9lumqZJP3gq",
	"oUgVC6rkxj4+59j3JDNIRS4FR240JDPQ6QRz4n5eKcPSDK8VEoP3+DpFbex1qYREZRi6qidBC/vfFBIh",
	"AW0U42OYh0DJ6nXGDY5R2Ru54GbSfovju5ZEorK3/1b4DAn8FVUIowW8aLQsnIdQIFFt481DUPg6ZQop",
	"JA/V4EMKoce9eLbE5EE/huVI4ukFU2OnWHBxj1oKrvEQNDB6XPQwy8oBOPol6ff1S2NR/yol1GbZc9Sa",
	"jLFlQWvsloVtxI1WV1EfPxXZNOcjkmMrZ5s8ZJjJ9gDlJPe14epUW0HuOA92IN4T2UdBbVboCBncsUP+",
	"nMG1Ke0lxp+FK/ZPwZ0Irn4Mg5+Yy4wYi/oNlWaCQwL9XtyL7RRCIieSQQLnvbh3DiFIYiYOXET8Lnew",
	"hYdvwRPDBB9SSMD7Y3EYgKcLtRks9n0quEHuniNSZix1T0Yv2kIo+8+u7dzamuZ1cYyaorvgneHQn8X9",
	"Q2NYOs9NT1GniknjCfX4qKX0Io4PNnP9TGqZd0BoULESgp7mOVHFElFAAo7vQSmlLSl1jWaMzi0Aihka",
	"bMp7464vFj8oXJ+QRJEcDSoNycMMmMVgHWMbirOx3yd1bcKV1TZO4seGcBce1OoyRyK4XvD5pQzbuS+6",
	"m3skTHArppyuaeuVCQgvhQ2eimB4Y/GNsWWj3qHpXsa4y/33/38nY3ihW10hiUknTV/49tSJNT6tM9Rb",
	"7F6doVNnenz0ZM8lFy0OtW2plvC3BY4qRH+OsTbk345DRzPwfr/YUUlaV3jP6LGk4BQ+jjB8VOruTh9f",
	"oWTc7VY8JRDnjlvGaZsztiaQjuzxia3iS1PIXv485ZBmDmkatdmmytdlp9qOtys9KEa1z6rHd84xg7n+",
	"cKxdfnAiSpHidPxVX/iCra9iWVYmXW0dVtnNec3Wo3or3TFVGSQwMUYmURT33F9yGV/GEZEseuvDPFwr",
	"ykRKsonQZntZ/+wfN1q/XvY4/x0AAP//qzCoIBMaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
